---
- name: Test the inventory script
  hosts: azure
  vars:
    f5_username: "{{ansible_env.f5_username}}"
    f5_password: "{{ansible_env.f5_password}}"
  connection: local
  gather_facts: yes
  tasks:
#    - debug: msg="{{ansible_host}}"
    - name: check failover status
      bigip_command:
       server: "{{ ansible_host }}"
       user: "{{f5_username}}"
       password: "{{f5_password}}"
       commands:
        - show /sys failover
      register: failover
      delegate_to: localhost
#    - debug: msg="{{failover.stdout}}"
#      when:
#       - '"active" in failover.stdout|first'
    - name: Save the running configuration of the BIG-IP
      bigip_config:
         save: yes
         server: "{{ ansible_host }}"
         user: "{{ f5_username }}"
         password: "{{ f5_password }}"
      delegate_to: localhost
    - name: trigger failover
      bigip_command:
       server: "{{ ansible_host }}"
       user: "{{f5_username}}"
       password: "{{f5_password}}"
       commands:
        - run /sys failover standby traffic-group traffic-group-1
      when:
       - '"active" in failover.stdout|first'
      delegate_to: localhost
#    - debug: msg="{{ inventory_hostname }} has powerstate {{ powerstate }}"
#    - shell: "f5-rest-node /config/cloud/azure/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/scripts/failoverProvider.js"
